# ---------------------------------------------------------
# Configuration file for http://travis-ci.org/#!/karmi/tire
# ---------------------------------------------------------

script: "bundle exec rake test:unit"

rvm:
  - 1.8.7
  - 1.9.3
  - ree

notifications:
  disable: true
