# ---------------------------------------------------------
# Configuration file for http://travis-ci.org/#!/karmi/tire
# ---------------------------------------------------------

language: ruby

rvm:
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - ree
  - jruby-19mode

env:
  - TEST_COMMAND="rake test:unit"
  - TEST_COMMAND="rake test:integration"

script: "bundle exec $TEST_COMMAND"

services:
  - elasticsearch
  - redis
  - mongodb

matrix:
  exclude:
    - rvm: 1.8.7
      env: TEST_COMMAND="rake test:integration"
    - rvm: ree
      env: TEST_COMMAND="rake test:integration"
  allow_failures:
    - rvm: ree

notifications:
  disable: true
